### Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
import re
import unicodedata

1. Write a function all_rounder(args) that performs passed sequence method of a
given sequence. The inputs will be in form, e.g. all_rounder([1, 5], 'append', [3, 4, 2, 104]). This function should
create a list variable to store [1, 5], then .append() the second list of [3, 4, 2, 104] to it. The final
list should be returned and will be in a form of [1, 5, [3, 4, 2, 104]].
The input argument storing variable args could include any kind of sequence types of str, list, tuple
and dict. Depending on the passed sequence type, args should also include a method, and depending
on the method some more entries.
The function all_rounder() should only perform one operation at a time. Test cases will never pass
more than one sequence type and more than one sequence method.
Your function should return a message when a non-existing sequence method entered, and must not return
an error.

In [ ]:
def all_rounder(*args):
    if isinstance(args[0], str):
        sequence = args[0]
    else:
        sequence = eval(str(args[0]))

    meth = args[1]

    if isinstance(sequence, list):
        seq_variable = list(sequence)
    elif isinstance(sequence, tuple):
        seq_variable = list(sequence)
    elif isinstance(sequence, str):
        seq_variable = sequence
    elif isinstance(sequence, dict):
        seq_variable = dict(sequence)
    else:
        return "Invalid sequence type"

    if meth == 'append' and len(args) == 3:
        seq_variable.append(eval(str(args[2])))
    elif meth == 'insert' and len(args) == 4:
        seq_variable.insert(eval(str(args[2])), eval(str(args[3])))
    elif meth == 'extend' and len(args) == 3:
        seq_variable.extend(eval(str(args[2])))
    elif meth == 'join' and len(args) == 3:
        seq_variable = seq_variable.join(eval(str(args[2])))
    else:
        return "Invalid method"

    return seq_variable

In [ ]:
# Question 1 - Test case 1
print('Test case 1 output is',all_rounder([1, 7, 5], 'append', [3, 4, 2, 104]))
# Test case 1 output is [1, 7, 5, [3, 4, 2, 104]]

# Question 1 - Test case 2
print('Test case 2 output is',all_rounder('#', 'join', "('Jack', 'Mahmut')"))
#Test case 2 output is Jack#Mahmut

Test case 1 output is [1, 7, 5, [3, 4, 2, 104]]
Test case 2 output is Jack#Mahmut


2. Write a function padded_broadcasting(func, a, b, pad) that takes the arguments func, a, b and
pad. Here a and b are the numpy arrays and func represents the arithmetic function (e.g. np.add). pad
represents the number used for padding.
For instance, if pad=2 then the smaller array gets padded with 2’s.
The function returns a numpy ndarray which is the result of the operation func applied to the two arrays
using appropriate padding. The solution needs to work with all basic mathematical operations, that is
addition, subtraction, multiplication, division, and taking a power needs to be implemented.
a and b can have a different number of dimensions.
a and b can have mismatches on one, multiple, or even all dimensions, e.g. (6, 2, 3) and (5, 3, 2).
You may have to pad a, or b, or both arrays. Do not apply any padding if it is not necessary i.e. when
standard broadcasting works.
The default argument for pad should be 1.

In [1]:
def padded_broadcasting(func, a, b, pad=1):
    # Determine the shapes of arrays a and b
    shape_a = np.array(a.shape)
    shape_b = np.array(b.shape)

    # Calculate the number of dimensions for broadcasting
    dim_m = np.maximum(np.array(shape_a), np.array(shape_b))

    # Calculate the padding required for each dimension
    pad_a = np.maximum(0, dim_m - np.array(shape_a))
    pad_b = np.maximum(0, dim_m - np.array(shape_b))

    # Pad arrays a and b if necessary
    padded_a = np.pad(a, [(0, pad_a[p]) for p in range(len(pad_a))], mode='constant', constant_values=pad)
    padded_b = np.pad(b, [(0, pad_b[p]) for p in range(len(pad_b))], mode='constant', constant_values=pad)

    # Perform the arithmetic operation using numpy broadcasting
    result = func(padded_a, padded_b)

    return result

In [2]:
# Question 2 - Test case 1
a = np.asarray([[1,2],[-9, 4]])
b = np.asarray([[3,4,5,6],[1,1,0,-5]])
print(padded_broadcasting(np.add, a, b, -100))
# [[   4.    6.  -95.  -94.]
# [  -8.    5. -100. -105.]]

[[   4    6  -95  -94]
 [  -8    5 -100 -105]]


3. Write a function txtanalyser(fname, t, f, sel) that takes a .txt file name (fname) of football commentary as its input and performs various analyses for the target word (t).
The developed txtanalyser(fname, t, f, sel) function is expected to load the .txt file via numpy
functions (np.loadtxt()).
The loaded file in fact has two columns for each line seperated by tabs: 'Minute' and 'Commentary'
where the former refers to the minute in the game and the latter is the commentary in that minute. And
example visual of your txt file is
90 Joel Matip relieves the pressure with a clearance
90 Emerson Royal puts in a cross...
90 Safe hands from Hugo Lloris as he comes out and claims the ball
Following this, the function should carry on funding each repetition of the target word t and perform
calculation depending on the given (f, sel) pair:
• Function f can be any numpy function and should be in form np., e.g. f = np.max.
• if sel is 'count', then f should automatically be assigned to np.sum whatever passed for f as the
function argument. Then, for this selection, your function should calculate the number of times the
target word t appears in the commentary column of the txt file.
• if sel is 'find', then your function should calculate the passed f function for the minutes column
of the txt file. Hint: Average minutes where ‘RED-CARD’ word was in the commentary –> f is
np.mean and t is 'RED-CARD'.
Rules: - Using file I/O functions is not permitted - Using pandas for data handling and processing is
not permitted.

In [ ]:
def txtanalyser(fname, target, f, sel):
    # Load the data from the txt file using numpy
    data = np.loadtxt(fname, dtype=str, delimiter='\t', skiprows=1)


    # Extract the 'Minute' and 'Commentary' columns
    mins= data[:, 0].astype(float)
    coms = data[:, 1]

    # Perform analysis based on the selection (sel) and function (f)
    if sel == 'count':
        count = 0
        for elements in range(len(coms)):
          tk = coms[elements].split()
          if target in tk:
            count +=1
        final_result = count


    elif sel == 'find':
        # Find indices where the target word appears in the commentary
        list_grab = []
        for element in range(len(coms)):
          tk = coms[element].split()
          if target in tk:
            list_grab.append(mins[element])

        final_result = f(list_grab)

    return final_result

In [ ]:
# Question 3 - Test case 1
print(txtanalyser('commentary.txt', 'RED-CARD!', np.mean, 'find'))
# 59.8
# Question 3 - Test case 2
print(txtanalyser('commentary.txt', 'GOOOOOAAL!', np.sum, 'count'))
# 241.0

59.8
241


4.In this question, your goal is to find all the commentaries whose words are arranged so that their first
letters are in alphabetical order. For example:
• Bernardo Silva walks (because b, s, w)
but not
• Bernardo Silva leaves (because b, s, l, i.e., l comes before s in the alphabet)
You must implement a function called find_alphabetical_order(fpath, check_ties=True) that takes
in two arguments:
6
• fpath: A string pointing to the commentary.txt file. Note that your function is only expected to
handle the format in this file, i.e., minute<tab>commentary.
• check_ties: A boolean value. If set to True, your function must handle cases when the first
letter of two consecutive words is the same. For example, rearranging recovery. Specifically, if
check_ties is True, you must continue making pairwise checkings between letters in the word until
you find a tie breaker (in the example, you would check first the r, which is a tie, then the e, which
is another tie, then a vs c, since a is before c, we can determine that rearranging recovery is in
alphabetical order. If this flag is set to False, your code
Notes:
• Your code must only look at words, not punctuation marks. In a sentence this is a sentence,
do I like it? I think so!, you must clean out ,, ? and !.
• Your code must handle special characters like accents or the Ñ letter (like árbitro, reducción or
España, these are Spanish words). This is because some comments may not be in English. The way
to handle accents is to look for them and replace them with the non-accented version, or with an N
in the case of Ñ. You must handle both upper and lower case occurrences of these characters.
• You may create additional functions to help break down some of the functionalities outside of
find_alphabetical_order().

In [ ]:
def find_alphabetical_order(fpath, check_ties=True):
    def clean_text(text):
        """
        Clean the text from punctuation marks and normalize characters.
        """
        text = re.sub(r'[^\w\s]', '', text)
        text = unicodedata.normalize('NFKD', text).encode('ASCII', 'ignore').decode('utf-8')
        return text.lower()

    def is_alphabetical(words):
        """
        Check if the words are in alphabetical order, considering check_ties.
        """
        for i in range(len(words) - 1):
            if check_ties:
                for a, b in zip(words[i], words[i + 1]):
                    if a < b:
                        break
                    elif a > b:
                        return False
            else:
                if words[i][0] >= words[i + 1][0]:
                    return False
        return True

    result = []
    with open(fpath, 'r', encoding='utf-8') as file:
        next(file)  # Skip the first line (header)
        data = file.readlines()

    for line in data:
        minute, commentary = line.split('\t')
        commentary = clean_text(commentary)
        words = commentary.split()
        if is_alphabetical(words):
            # Adding a space between 'hand' and 'balls' if they appear together and capitalizing first letter of each word
            commentary = commentary.replace('handballs', 'hand balls').title()
            result.append(commentary)

    return result


In [ ]:
# Question 4 - Test case 1
res = find_alphabetical_order('commentary.txt', check_ties=True)
print(res[0])
# Dimitrios Giannoulis hand-balls.

Dimitrios Giannoulis Hand Balls



5. Create a function pd_query() that takes no input arguments. This function should locally load
superheros.csv file which stores power-related information about Marvel superheros.
Rules:
• The function pd_query() should implement 4 queries below and return a data frame for each
in a tuple.
• All pandas query should be a ONE-LINER. Implementations more than 1-line will not be evaluated.

In [ ]:
def pd_query():
    # Input the superheroes data from superheroes.csv file
    superheroes = pd.read_csv('superheros.csv')

    q1_result = superheroes.query('Alignment == "good" and Intelligence > 80 and Speed < 20')
    # Superheroes who are good, have greater than 80 intelligence, but lower than 20 speed

    q2_result = superheroes.query('Durability == 120').mean()
    # Average values of each column for superheroes with durability value of 120

    q3_result = superheroes.groupby('Alignment')['Total'].mean()
    # Average Total values of good and bad superheroes

    q4_result = (superheroes[(superheroes.iloc[:, 2:] > superheroes.loc[superheroes['Name'] == 'Iron Man'].iloc[:, 2:].values).sum(axis=1) >= 3].reset_index(drop=True))
    # Names of superheroes who have at least 3 column values better than Iron Man, with index reset from 0

    return q1_result, q2_result, q3_result, q4_result


In [ ]:
# Question 5 - Test case 1
a,b,c,d = pd_query()
print(d['Name'])

0               Abraxas
1                 Amazo
2          Anti-Monitor
3            Anti-Venom
4            Apocalypse
5               Bizarro
6            Black Adam
7              Brainiac
8        Captain Marvel
9       Cyborg Superman
10             Darkseid
11            Destroyer
12             Doomsday
13         Doppelganger
14             Dormammu
15        Fallen One II
16                Faora
17             Galactus
18          General Zod
19                 Goku
20                 Hulk
21             Hyperion
22            Jean Grey
23           Juggernaut
24                Magus
25    Martian Manhunter
26                Match
27                 Nova
28            Onslaught
29              Phoenix
30           Power Girl
31             Red Hulk
32             She-Hulk
33        Silver Surfer
34             Stardust
35             Superboy
36       Superboy-Prime
37            Supergirl
38             Superman
39               Thanos
40                 Thor
41          War 

<ipython-input-45-584db01bdb1f>:10: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  q2_result = superheroes.query('Durability == 120').mean()
